pw.println("<!Doctype html>");
pw.println("<html lang='en'>");
pw.println("<head>");
pw.println("<script src='/OnlineCompiler/ja.js'>");
pw.println("</script>");
pw.println("<style>");
pw.println("#upper");
pw.println("{");
pw.println("position: absolute;");
pw.println("");
pw.println("    width:1370px;");
pw.println("    border: 1px solid grey;");
pw.println("   background-color:grey;");
pw.println("   color:white;");
pw.println("");
pw.println("height:40px;");
pw.println("}");
pw.println("");
pw.println("#statusCaption");
pw.println("{");
pw.println("position: absolute;");
pw.println("top:300px;");
pw.println("left:55px;");
pw.println("");
pw.println("}");
pw.println("");
pw.println("#status");
pw.println("{");
pw.println("position: absolute;");
pw.println("top:315px;");
pw.println("left:120px;");
pw.println("");
pw.println("}");
pw.println("");
pw.println("#codeblock");
pw.println("{");
pw.println("position: absolute;");
pw.println("top:75px;");
pw.println("left:50px;");
pw.println("    width: 580px;");
pw.println("    border: 4px solid grey;");
pw.println("    padding: 0px;");
pw.println("    margin: 5px;");
pw.println("border-radius:10px");
pw.println("}");
pw.println("");
pw.println("#errorSection");
pw.println("{");
pw.println("position: absolute;");
pw.println("top:370px;");
pw.println("left:50px;");
pw.println("    width: 580px;");
pw.println("    border: 4px solid grey;");
pw.println("    padding: 0px;");
pw.println("    margin: 5px;");
pw.println("border-radius:10px");
pw.println("}");
pw.println("");
pw.println("");
pw.println("");
pw.println("");
pw.println("</style>");
pw.println("</head>");
pw.println("<body>");
pw.println("<div id='upper'>");
pw.println("<a href='' style='color:white;font-size:200%;text-decoration:none' > CodePad</a>");
pw.println("</div>");
pw.println("");
pw.println("<center>");
pw.println("");
pw.println("<form onsubmit='return validateForm(this)' action='/OnlineCompiler/compiler'>");
pw.println("<div id='codeblock'>");
pw.println("<textarea rows='15' cols='79' id='code' name='code' style='border: 0px solid black;'>");
pw.println("");
pw.println("#include<stdio.h>");
pw.println("int main()");
pw.println("{");
pw.println("retun 0;");
pw.println("}");
pw.println("</textarea>");
pw.println("</div>");
pw.println("<div id='statusCaption' >");
pw.println("<p style='color:green;font-size:150%'>Status:</p>");
pw.println("</div>");
pw.println("<div id='status' >");
pw.println("<p style='color:red;font-size:100%'>Compilation Error</p>");
pw.println("</div>");
pw.println("<div id='errorSection'>");
pw.println("<textarea rows='15' cols='79' id='code' name='code' style='border: 0px solid black;'></textarea>");
pw.println("</div>");
pw.println("");
pw.println("</form>");
pw.println("");
pw.println("");
pw.println("</body>");
pw.println("</html>");

